### ISSUE TITLE
UI lag when followed channels are refreshed (?)

### ISSUE THREAD

**Issue by dengelt** [vinszent/gnome-twitch#260]
I noticed (semi) regular UI lags (i.e. not only the video is lagging, but also chat, the headerbar, etc.). It seems to happen on all quality settings. I'm not 100% sure what's causing it, but outside of the player it also happens when the follower thumbnails are refreshed. Also it doesn't seem to happen when I'm not logged in to Twitch, so I suspect it has to do with the follower thumbnails being refreshed.

**Comment by vinszent** [comment]
I think the thumbnails are being resized on the main thread 😛 . I'll fix it over the weekend, thanks for reporting.

**Comment by ptkato** [comment]
It's making the app unusable here. The weirdest thing is that the audio plays just fine.

**Comment by vinszent** [comment]
Sorry for the delay, but this should fix it. I've been having issues with one of the libraries (libsoup) which isn't as thread safe is it claims to be.

**Comment by TingPing** [comment]
@vinszent libsoup has async APIs, why would you be using threads manually at all?

**Comment by vinszent** [comment]
@TingPing I do [use](https://github.com/vinszent/gnome-twitch/blob/master/src/gt-resource-downloader.c#L438) libsoup's async functions. The reason I use threads is for caching, as I only download the headers and check whether the image actually needs to be downloaded or not. That however puts me back on the main thread and I need to do the downloading in a separate thread.

I know libsoup has a built in cache but it only works with the async API and I use the sync API in some places. That's why I've written a simple cache myself that works with both in both async and sync.

**Comment by Techwolf** [comment]
Wow... https://github.com/vinszent/gnome-twitch/commit/44cfb7daa68e83b512a36fda05c6125218ad59e8 made a huge difference on my system. It now comes up nearly instantly and no longer freezes loading a bunch of thumbnails.

**Comment by vinszent** [comment]
@Techwolf Glad to hear 😄 . Unfortunately I don't have a lot of time to do thorough testing and these issues do slip through.
