### ISSUE TITLE
split off libgnome-twitch not only in windows

### ISSUE THREAD

**Issue by grindhold** [vinszent/gnome-twitch#301]
https://github.com/vinszent/gnome-twitch/blob/5730b871abef3415671443c86eb5f3b00dc32bdb/src/meson.build#L111

i am currently trying to write a plugin against gnome-twitch in vala. this line gives me a hard time. why not just creating the pkgconfig-file and installing it? that would make my life a lot easier. as my plugin is in vala and the main application is in c, i do not want to consider merging it back here, because bloating the buildsystem with another language does not seem very elegant to me. maybe other people also want to write python- or lua-plugins, as libpeas is very flexible here. an easy possibility to write plugins in independent repositories would make much sense.

please consider installing the library and it's little helperfiles (pkgconfig, headerfiles, maybe even GIR-files) instead of just linking it into the executable. it would greatly server modularity.

**Comment by vinszent** [comment]
Sure I can look into it, might ditch Windows support all together as it's just waaay to much work. But I'm pretty sure the reason I did this is that on Linux systems you can compile with undefined references while on Windows you can't. So that's why I only create libgnome-twitch on Windows so that plugins can link against that and on Linux they don't need to link against anything, the symbols will be defined at runtime.

On a side note, it's great that you want to write a plugin! I currently only expose the player backend API but I'm looking to add more things, especially a chat API. If you need any help or have suggestions, just let me know 👍 .

**Comment by grindhold** [comment]
#302 should fix this now

**Comment by grindhold** [comment]
fixed with merge of #302
