### ISSUE TITLE
Enable MPV backend

### ISSUE THREAD

**Issue by bennylb** [vinszent/gnome-twitch#80]
Hi there,

I've uncommented the relevant lines in the `meson.build`:
```meson
dependency('mpv'),
dependency('epoxy')]
'gt-player-mpv.c',
```
and the following in `gt-win.c`:
```c
#include "gt-player-mpv.h"
GT_TYPE_PLAYER_MPV;
```
It compiles without error but no mpv. Is the mpv backend incomplete or am I missing something to enable this feature?

Thanks in advance.

**Comment by Ippytraxx** [comment]
It's incomplete atm. I was just testing to see if it was even possible to have a mpv backend. After I finish up the rest of the Twitch integration then this is probably what I'll work on next.

**Comment by bennylb** [comment]
Ok thanks for explaining.

**Comment by dchristidis** [comment]
If I may ask, what are the limitations of GStreamer that prompted the need for the mpv backend?

**Comment by Ippytraxx** [comment]
@dchristidis Nothing in particular just a lot of people just like mpv ;). GStreamer to some people might feel like unnecessary bloat especially on non-GTK environments while mpv is just a single dependency. 

Mainly just testing whether it would work to have multiple backends, that's why the GtPlayer class exists in the first place to provide an abstraction for multiple player backends. No idea if it will actually pan out or not but it would be nice.

**Comment by dengelt** [comment]
Not really a limitation, but a mpv backend could make use of vapoursynth (for frame interpolation for example). I don't know if gstreamer can be used with vapoursynth, but if not, that would be a use case for an mpv backend.

**Comment by Ippytraxx** [comment]
MPV backend is now up and running, as well as 3 other ones. Check 'em out in the develop branch! Instructions on how to build in the readme.

I'll close this once it's merged to master.

**Comment by ert65** [comment]
Is it possible to make mpv backend to use hardware acceleration or somehow to read from mpv.conf and look for options(hwdec= ) there, like the mpv player itself?

**Comment by vinszent** [comment]
Currently no, the MPV backend is just kind of a "tech preview". I'm planning on implementing custom options through command line string and conf file in the next release.
